export const scoops = [
  {
    name: "Jen234",
    date: "20 mins",
    image: "/assets/images/scoop_1.jpg",
    caption: "Look who we saw",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "Kolade",
    date: "20 mins",
    image: "/assets/images/scoop_2.jpg",
    caption: "Love this show 💗",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "ellen45",
    date: "20 mins",
    image: "/assets/images/scoop_3.jpg",
    caption: "Special guest for tonight's show 🏀 ",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "bigbrad01",
    date: "20 mins",
    image: "/assets/images/scoop_4.webp",
    caption: "Bahamas ☀️",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "Chrissy",
    date: "20 mins",
    image: "/assets/images/scoop_5.jpeg",
    caption: "Who is this Queen 👑 ?",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "blacksanta34",
    date: "20 mins",
    image: "/assets/images/scoop_6.jpg",
    caption: "Prom night yall 💃",
    likes: 21,
    comments: 5,
    share: 0,
  },
  {
    name: "collegedropoutt24",
    date: "20 mins",
    image: "/assets/images/scoop_7.jpg",
    caption: "I guess we'll never know 🏆...",
    likes: 21,
    comments: 5,
    share: 0,
  },
];
